### ISSUE TITLE
Can this be used to update the app without passing by the app stores?

### ISSUE THREAD

**Issue by etiennea** [phonegap/phonegap-plugin-contentsync#10]
I see this plugin works, but the files are in /Documents. They must be moved elsewhere to replace the index.html?

**Comment by mwbrooks** [comment]
We're still working on this plugin, so everything hasn't been finalized. As it stands, when the `complete` event fires, it will return a `data.localPath`. This path will be different on every platform, but it's the persistent path to where your app is stored and the file path is formatted to be compatible with the browser. As a result, you should be able to point a Cordova browser to `data.localPath + '/index.html` to load the sync'd app.
