### ISSUE TITLE
Support for Windows 10 apps

### ISSUE THREAD

**Issue by R2D221** [phonegap/phonegap-plugin-contentsync#105]
Currently the plugin only works for Windows Phone 8. In order to provide the same app experience in all devices, it would be great to have a Windows 10 implementation.

**Comment by mwbrooks** [comment]
Hi @R2D221, we have some work-in-progress to add Windows Universal support. You can follow and/or contribute from the following pull request:

https://github.com/phonegap/phonegap-plugin-contentsync/pull/104
