### ISSUE TITLE
I keep getting an error on 97% on iOS

### ISSUE THREAD

**Issue by etiennea** [phonegap/phonegap-plugin-contentsync#11]
2015-04-01 14:56:04.282 myapp[7801:3871780] Sync Failed - *** -[NSURL initFileURLWithPath:]: nil string parameter

**Comment by mwbrooks** [comment]
@etiennea thanks for kicking the tires! Any chance that you can provide us with more detail so that we can create the issue? A full log would help along with the source package that you're using and whether you're testing on a simulator or device. /cc @imhotep

**Comment by imhotep** [comment]
Yes! All of that and more please! Especially I want to see what your JS code looks like ! Thanks!

**Comment by etiennea** [comment]
My log is here

2015-04-01 14:55:49.437 president[7801:3871618] Downloading and unzipping from https://github.com/timkim/zipTest/archive/master.zip
2015-04-01 14:55:49.448 president[7801:3871618] THREAD WARNING: ['Sync'] took '10.441895' ms. Plugin should use a background thread.
2015-04-01 14:56:03.730 president[7801:3871824] Task: <__NSCFBackgroundDownloadTask: 0x144519380>{ taskIdentifier: 1 } completed successfully
2015-04-01 14:56:04.281 president[7801:3871780] unzipped path /var/mobile/Containers/Data/Application/E721E6E8-B808-4540-A3A6-7D3E216DF4AD/Documents/myapps/myapp
2015-04-01 14:56:04.282 president[7801:3871780] Sync Failed - *** -[NSURL initFileURLWithPath:]: nil string parameter

My js is uninteresting at this stage but here goes
    
    var updatePhonegapApp = function() {
		var url = "https://github.com/timkim/zipTest/archive/master.zip";
		var sync = ContentSync.sync({
			src: url,
			id: 'myapps/myapp',
			type: 'replace',
			copyCordovaAssets: true
		});

		var setProgress = function(progress) {

			if (progress.status) {
				console.log(progress.status == "Downloading" ? "Downloading..." : "Extracting...");
			}
			if ($('#minialert').css('display') === 'none') {
				$('#minialert').show().velocity("transition.slideDownIn");
			}
			if (progress.progress) {
				$('#minialert').html(progress.status + ' ' + progress.progress + '%');
			} else {
				$('#minialert').html(progress.status);
			}
		};

		sync.on('progress', function(progress) {
			console.log("Progress event", progress);
			setProgress(progress);
		});
		sync.on('complete', function(data) {
			setProgress({
				progress: 100
			})
			console.log("Complete", data);
			document.location = data.localPath + "/zipTest-master/index.html";
		});
		sync.on('error', function(e) {
			console.log("Error", e);
			$('#minialert').html('Error:'+ e);
			setTimeout(function() {
				$('#minialert').velocity("transition.slideUpOut");
			}, 1200);
		});
	}
      if(appVersion != api.version) updatePhonegapApp();

**Comment by etiennea** [comment]
Any idea? Do you need more info?

**Comment by imhotep** [comment]
@etiennea Can you tell me if the sample app provided with the plugin (under sample/) works for you ? Excuse the language in it btw.

**Comment by etiennea** [comment]
Yes with the new update it works now. Small bug is that under 50% when I download a file a second time it says 1234042 well huge numbers rather than percentages. Looks like the number of bytes or smth.
