### ISSUE TITLE
how persistent is the content once synced?

### ISSUE THREAD

**Issue by josh-m-sharpe** [phonegap/phonegap-plugin-contentsync#118]
I can't seem to find anything in the README that states how long I can trust that synced content will be on the device.  Are there any guarantees the OS won't randomly wipe one of my files behind the scenes?

Thanks!

**Comment by timkim** [comment]
Hi @josh-m-sharpe 

I believe that synched content should persist until you delete the app. I don't think the OS will randomly delete content - so far I haven't run into issues regarding that. Maybe you'll run into such an issue if you have so much synch'd content that you start running out of space.

**Comment by josh-m-sharpe** [comment]
Thanks for the response!!
