### ISSUE TITLE
Not working on iOS 9.3.1?

### ISSUE THREAD

**Issue by graphicgeek** [phonegap/phonegap-plugin-contentsync#119]
Seems to work just fine on Android, but since the latest update of iOS (to 9.3.1) the .sync method does nothing. No error messages, or log output that I can see, but the sync doesn't run. Suggestions?

**Comment by timkim** [comment]
Hi @graphicgeek 

I've been using iOS@9.3.1 (tested on 4s and on a 5) and everything seems ok on my end. I would check your server logs to see if it is actually connecting.

**Comment by vernondegoede** [comment]
Works for me as well.

**Comment by macdonst** [comment]
@graphicgeek sorry we can't reproduce. Please feel free to re-open with more info.

**Comment by graphicgeek** [comment]
I've been working on other projects, but finally came back to this. Turns out it was just a stupid mistake on my part. I was passing an integer as the id property instead of a string, which caused the plugin to do nothing. I converted to a string, and it works fine.

Thanks!
