### ISSUE TITLE
When the files already exist on iOS stops on 50%

### ISSUE THREAD

**Issue by etiennea** [phonegap/phonegap-plugin-contentsync#12]
I think the zip operation cannot overwrite or something

**Comment by imhotep** [comment]
Please share the javascript you're trying to run. Thanks

**Comment by etiennea** [comment]
I have posted my js in issue #11 don't see anything wrong with it. It just get stuck on 50% the second time I do it.

**Comment by etiennea** [comment]
Works not still a small bug see #11
