### ISSUE TITLE
windows phone 8.1 redirect to extracted content

### ISSUE THREAD

**Issue by hosshoss** [phonegap/phonegap-plugin-contentsync#135]
Hello,

I have manage to make the plugin works in both android and iOS.

I tried to run code on windows phone 8.1 "windows platform", it successfully downloaded the new content and extracted it in data directory, but when I tried to redirect to the new downloaded html in data directory using this code:

`  sync.on('complete', function (data) {
             path = data.localPath;
            window.location.replace(path + "\\app\\index.html");
        });
`

it gives me this error:

> APPHOST9624: The app can’t use script to load the file:///C:/Data/Users/DefApps/APPDATA/Local/Packages/com.xx.xxx_bzbj8h50hftv4/LocalState/app/index.html url because the url launches another app. Only direct user interaction can launch another app.

I even tried to use   window.location.href = path;

I tried to check availability of using this API :
`   ContentSync.loadUrl('file://' + data.localPath, function() {
        console.log('success');
    });`

but it seems this is not implemented in for windows platform

So my question is "How can I redirect to the new index.html in windows phone 8.1 ?"

Thanks for your support

**Comment by dmaus** [comment]
I had the same problem, but there is no soloution yet.
 #128 "Unfortunately Windows does not allow this functionality."
