### ISSUE TITLE
Sync api on universal windows platform

### ISSUE THREAD

**Issue by seematalanki** [phonegap/phonegap-plugin-contentsync#139]
Hi,
I see that the project source has files related to windows universal app even though the documentation says wp8.
The plugin reaches till startDownload function and calls download.startAsync(), but does not fire complete, error or progress handlers.

**Comment by timkim** [comment]
Hi @seematalanki 

Sorry about the long reply, but I believe those files associated with the Windows Universal app were some discovery work to see if we could get things working on WP10. 

This plugin is for WP8 and WP8.1 only.
