### ISSUE TITLE
Error in downloading a zip from URL on Android

### ISSUE THREAD

**Issue by timkim** [phonegap/phonegap-plugin-contentsync#14]
When I initiate a download on Android it throws a puzzling error:

```
D/ContentSync( 4926): sync called with id = bu and src = http://192.168.43.139:3000/__api__/zip!
D/ContentSync( 4926): download http://192.168.43.139:3000/__api__/zip
E/ContentSync( 4926): prefix must be at least 3 characters
```

**Comment by macdonst** [comment]
Okay, for some reason in Java if you call File.createTempFile(String prefix, String suffix, File directory) the call will fail if "prefix" is less than 4 characters. I have no idea why they coded it this way and I don't care to look through the source. I now pad the prefix so it is always greater than 4 characters.

**Comment by timkim** [comment]
Hrm, it appears there are some more errors:

```
D/ContentSync( 2785): sync called with id = bu and src = http://192.168.43.139:3000/__api__/zip!
D/ContentSync( 2785): download http://192.168.43.139:3000/__api__/zip
D/ContentSync( 2785): Download file:http://192.168.43.139:3000/__api__/zip
D/ContentSync( 2785): Target file:/data/data/io.cordova.hellocordova/cache/cdv_bu1364836324.tmp
D/ContentSync( 2785): size = 0
D/ContentSync( 2785): bytes read = 4
```
Looks like it starts the download but finishes at size 0?

**Comment by timkim** [comment]
Oh this issue has been fixed I believe from this commit: https://github.com/phonegap/phonegap-plugin-contentsync/commit/2beebfe9e93eb6457661f43c8da053795b468338

Whatever Simon did in the refactor makes it work!
