### ISSUE TITLE
Sync on complete always returns TRUE cached flag.

### ISSUE THREAD

**Issue by kleeb** [phonegap/phonegap-plugin-contentsync#147]
On the first run of the app I am running 

`var sync = ContentSync.sync({id: 'app', type: 'local'});`
`sync.on('complete', function(data) {...`

just to check if the app has cached data, and it properly responds with error

on the second and next runs however I am always getting data.cached=true, even though no data has been cached, which ends up with fatal error ERR_FILE_NOT_FOUND.

**Comment by timkim** [comment]
Hi @kleeb 

What version of the plugin are you using and on which platform?

**Comment by kleeb** [comment]
I am checking the latest version on Android 6.

And this looks weird for Android:

`result.put(PROP_CACHED, type.equals(TYPE_LOCAL))`

isn't it always true when we choose local sync?

Shouldn't it be more something like:

`result.put(PROP_CACHED, new File(outputDirectory + "/www/").exists())` ?
