### ISSUE TITLE
Percentage is very large number > 1000

### ISSUE THREAD

**Issue by etiennea** [phonegap/phonegap-plugin-contentsync#15]
Small bug is that under 50% when I download a file a second time it says 1234042 well huge numbers rather than percentages. Looks like the number of bytes or smth.

**Comment by macdonst** [comment]
@etiennea what platform(s) did you see this on can you give us a bit more detailed reproduction scenario?

**Comment by etiennea** [comment]
This was quite a few versions ago, might have been fixed. Basically during the unzipping it was displaying the amount of bytes or smth.
