### ISSUE TITLE
ios with basic auth fails at validation of url

### ISSUE THREAD

**Issue by mnewmedia** [phonegap/phonegap-plugin-contentsync#150]
Hi, since port 443 is already used for other stuff. I used port `80` which redirects to port `7070`.
I also use `basic auth`. But with both ports i'll get the error `Invalid src`. 
Example: 
```
http://sub.domain.com/image.zip -> https://sub.domain.com:7070/images.zip`
```

So I tried also other stuff:
Using Port `7070` without `basic auth` goes to 16 percent and then sticks in a loop with `task failed` error.

Using Port 80 without `basic auth` works.

My Basic Auth code:
```js
headers: {'Authorization': 'Basic ' + btoa('user:pass')},
```

Any ideas?

**Comment by mnewmedia** [comment]
I never used objective-c before but while trying to read the code i may found something:

```obj-c
// checking if URL is valid
NSURL *srcURL = [NSURL URLWithString:src];
NSMutableURLRequest *urlRequest = [NSMutableURLRequest requestWithURL:srcURL];
[urlRequest setHTTPMethod:@"HEAD"];
NSHTTPURLResponse *response = nil;
NSError *error = nil;
[NSURLConnection sendSynchronousRequest:urlRequest returningResponse:&response error:&error];
```
As far as i understand before downloading the content, you do just a synchronus request to check if the url is correct and the server gives answer. But i do not see anything about the basic auth here, so i suspect it will always return an error because the server responds with 403.

**Comment by mnewmedia** [comment]
My assumption was correct, tried, tested, and created a PR.

**Comment by macdonst** [comment]
Yeah, but don't close the issue until we get a chance to merge the PR.
