### ISSUE TITLE
Expose HTTP Response codes

### ISSUE THREAD

**Issue by arumsey** [phonegap/phonegap-plugin-contentsync#158]
The `ContentSync.ERROR_STATE` `INVALID_URL_ERR` does not provide enough information on why the sync failed since this error also includes response codes that are >= 400.

Would it be possible to expose the server HTTP response code during a sync so that a client could throw a more useful error message if it chooses?

**Comment by macdonst** [comment]
@arumsey can you give content sync a try from master and see if that fits your needs. If so I'll release a new version.

@imhotep when you get a chance give my iOS changes a quick review.
