### ISSUE TITLE
Need to set error timeouts on connection

### ISSUE THREAD

**Issue by timkim** [phonegap/phonegap-plugin-contentsync#16]
Whenever syncing to an url that doesn't actually return anything, sync will wait forever and not error out.

**Comment by timkim** [comment]
This is for iOS btw. I thought android might have the same problems but it just takes awhile for it to timeout.

**Comment by imhotep** [comment]
What should be the timeout ?

**Comment by timkim** [comment]
Hrm - 15 secs?

**Comment by OoDeLally** [comment]
Same here for Android
