### ISSUE TITLE
Replace of data after connection aborted (HTTP code 400 or 500)

### ISSUE THREAD

**Issue by kgmav** [phonegap/phonegap-plugin-contentsync#162]
this problem occours on Android

the download function in Sync.java returns a true if the connection get a HTTP code != 200. 
If the connection aborted the exception is catched here and after finaly the function is leave with a true  	in place of false

``` 
} catch (Throwable e) {
            try {
                sendErrorMessage(e.getLocalizedMessage(), CONNECTION_ERROR, callbackContext, connection.getResponseCode());
            } catch (IOException ioe) {
            }
        } finally {
            if (connection != null) {
                // Revert back to the proper verifier and socket factories
                if (trustEveryone && useHttps) {
                    HttpsURLConnection https = (HttpsURLConnection) connection;
                    https.setHostnameVerifier(oldHostnameVerifier);
                    https.setSSLSocketFactory(oldSocketFactory);
                }
            }
        }

        return true;
}
```

**Comment by macdonst** [comment]
@kgmav can you install the latest from `master` and let me know if it fixes your specific issue?

**Comment by bugsmafia** [comment]
/project/src/com/adobe/phonegap/contentsync/Sync.java:304: error: ';' expected
                    retval = false
                                  ^
/project/src/com/adobe/phonegap/contentsync/Sync.java:316: error: ';' expected
                                retval = false
                                              ^
/project/src/com/adobe/phonegap/contentsync/Sync.java:331: error: ';' expected
                            retval = false
                                          ^
/project/src/com/adobe/phonegap/contentsync/Sync.java:344: error: ';' expected
                                retval = false
                                              ^

**Comment by kgmav** [comment]
@macdonst yes that it's
