### ISSUE TITLE
contentsync/Sync.java:304: error: ';' expected

### ISSUE THREAD

**Issue by bugsmafia** [phonegap/phonegap-plugin-contentsync#163]
/project/src/com/adobe/phonegap/contentsync/Sync.java:304: error: ';' expected
                    retval = false
                                  ^
/project/src/com/adobe/phonegap/contentsync/Sync.java:316: error: ';' expected
                                retval = false
                                              ^
/project/src/com/adobe/phonegap/contentsync/Sync.java:331: error: ';' expected
                            retval = false
                                          ^
/project/src/com/adobe/phonegap/contentsync/Sync.java:344: error: ';' expected
                                retval = false
                                              ^

**Comment by ptit6sky** [comment]
Fixed in following pull request.

#164

**Comment by macdonst** [comment]
@bugsmafia @ptit6sky and this is why you shouldn't release code on a plane. I just pushed a 1.3.3 to npm.
