### ISSUE TITLE
net::ERR_FILE_NOT_FOUND on android

### ISSUE THREAD

**Issue by Frankobingen** [phonegap/phonegap-plugin-contentsync#180]
Synchronization seems to work quite well, however after the sync i do the following as shown in the example.

    sync.on('complete', function(data) {
            if(data.localPath) {
              var url = "file://"+data.localPath + "/www/index.html";
              alert('Sync complete ' + data + ' changing document.location ' + url );
              ContentSync.loadUrl(url);
              // document.location = url;
            }
     });

I've tried both - ContentSync.loadUrl and document.location. the loadUrl method doesn't seem to do anything. Document.location leads to 

**net::ERR_FILE_NOT_FOUND(file:///data/user/0/com.phonegap-helloworld/files/myapp/www/index.html)**

**Comment by macdonst** [comment]
@Frankobingen did you try:

```
var url = "file://"+data.localPath + "/index.html";
```

**Comment by putnal** [comment]
Im having same issue with sample

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
