### ISSUE TITLE
data.progress showing a long number

### ISSUE THREAD

**Issue by bshowy2k** [phonegap/phonegap-plugin-contentsync#183]
When downloading a zip file of around 200MB and containing around 100 images, the data.progress returns a long number of 9 digits, then increase to 10, then 11 digits. According the documentation, the data.progress should return a number between 0 and 100 but in this case is not happening

**Comment by timkim** [comment]
Hi @bshowy2k 

Which platform is this happening on?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
