### ISSUE TITLE
[iOS] calling sync() with options.copyCordovaAssets set does not perform copy

### ISSUE THREAD

**Issue by blefebvre** [phonegap/phonegap-plugin-contentsync#188]
### Expected Behaviour

When sync() is called with `copyCordovaAssets: true`, per the README I would expect the Cordova related assets (cordova.js, cordova_plugins.js and plugins/) to be copied to the sync'd directory. This works as expected on Android.

### Actual Behaviour

On iOS, once sync() is called the app prints "Requesting local copy of <id>", but does not actually perform the copy.

None of the event handlers (`complete`, `error`, or `progress` in my testing) are called.

### Reproduce Scenario (including but not limited to)

I've created a basic app that demonstrates this issue: https://github.com/blefebvre/phonegap-plugin-contentsync-copyCordovaAssets-bug

#### Steps to Reproduce

- Clone the demo repository: https://github.com/blefebvre/phonegap-plugin-contentsync-copyCordovaAssets-bug
- add the ios platform
- run the app from Xcode

Note how the app hangs on the "Initializing..." page, and none of the Content Sync event handlers are called.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 11

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

n/a

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 7.1.0
    cordova platform version ios                     # 4.5.4

#### Plugin version

    cordova plugin version | grep phonegap-plugin-contentsync   # 1.4.1

#### Sample Code that illustrates the problem

https://github.com/blefebvre/phonegap-plugin-contentsync-copyCordovaAssets-bug

#### Logs taken while reproducing problem

Last thing printed to the Xcode console is `Requesting local copy of synced`

**Comment by macdonst** [comment]
@blefebvre yup, that's a bug. It only works if `copyRootApp: true`. Feel free to send a PR for this 😈
