### ISSUE TITLE
When is sync fired...

### ISSUE THREAD

**Issue by cfjedimaster** [phonegap/phonegap-plugin-contentsync#19]
So, I will admit to not reading every word of the readme.md and if I missed this, I apologize. Is the plugin doing a HEAD against the URL and checking the date against an internal date before it fetches the content?

If so, should there be support for an event/status/etc of "I don't need to download this."

**Comment by timkim** [comment]
Hi @cfjedimaster 

The plugin isn't checking the date against anything - that's up to you to implement. Basically if you do a basic sync call like `var sync = ContentSync.sync({ src: 'http://myserver/assets/movie-1', id: 'movie-1' });` , it is always going to retrieve whatever zip is being returned at that src url you defined.

In the `PhoneGap Developer App`, we have an autoreload feature that detects when there's a change on the server. So the `PhoneGap Developer App` will constantly ping the server asking if the the files being served has changed or not. When the server detects a change, the client will then receive an outdated flag and begin a new content sync call. 

So this script gets injected to all of the .html files being served: [autoreload on client](https://github.com/phonegap/connect-phonegap/blob/master/res/middleware/autoreload.js) and that talks to this end point on the server: [autoreload on server](https://github.com/phonegap/connect-phonegap/blob/master/lib/middleware/autoreload.js).

The `options.type` flag can help you how to retrieve and update content in a variety of situations as well.  - `replace` will just overwrite everything - basically will delete the folder with your app in it (if it exists) and create it again
- `merge` will only add new content, replace existing files, and not delete any files
- `local` will return the file path and not download anything if it finds that the assets exist already (determined by the use of the `content sync id`, I believe)

**Comment by cfjedimaster** [comment]
Interesting. Does it make sense to make this more clear? I kinda assumed it *was* using some intelligence in terms of when to sync. I think it makes sense to not, but as I said, I just assumed it was.

**Comment by imhotep** [comment]
@cfjedimaster it is very app specific and can't be implemented by the plugin to cover every use case. I am going to close this issue for now.
