### ISSUE TITLE
Cached content is not found in localPath

### ISSUE THREAD

**Issue by ghadad** [phonegap/phonegap-plugin-contentsync#191]
The sync method is end with complete but there is no files in the app cache directory . Any clue ?
Thanks

**Comment by ghadad** [comment]
The sync method is end with complete but there is no files in the app cache directory . Any clue ? 
Thanks

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by ghadad** [comment]
Sorry about that. you're absolutely right.
