### ISSUE TITLE
Optional additional sync'd folders

### ISSUE THREAD

**Issue by hicksy** [phonegap/phonegap-plugin-contentsync#26]
I think it would be useful if we could specify additional folder(s) to sync over along with ```cordova.js```,```cordova_plugins.js``` and ```plugins/``` when using ```options.copyCordovaAssets: true```

A zipped ```www/``` folder will often contain assets that don't often require updating, so unnecessary to keep including these in the zipped folder. 

(e.g fonts, large JS libs such as ionic )

As an example, my built (and minified) ```www/``` folder zips to ~3mb, however, removing the ```lib``` directory and zipping reduces this down to 200k

I will be looking at using https://github.com/braddenver/preen to reduce ```lib/``` down further as a lot of this size is due to unnecessary files, but for me, best option would be to have it synced and not part of the remote zip.

Would this be feasible / sensible?

**Comment by imhotep** [comment]
Yes. We will be adding an option to copy over the whole app (not only cordova assets) to newly synced folder before applying update.

**Comment by imhotep** [comment]
@hicksy https://github.com/phonegap/phonegap-plugin-contentsync/tree/init

This will make it to master soon

**Comment by hicksy** [comment]
Great

Does this copy the root app into the synced folder prior to unzip? And therefore we will be able to overwrite folders by including in the zip? 

Also, assuming the root is always the original root of app as opposed to pointing to last synced folder?

**Comment by imhotep** [comment]
@hicksy Yes and Yes. You can try it out now. It's in master and npm (1.1.3). iOS only for now.

**Comment by macdonst** [comment]
@hicksy @imhotep Android works too.

**Comment by imhotep** [comment]
ah cool so I guess I can close this :)
