### ISSUE TITLE
Missing Command Error

### ISSUE THREAD

**Issue by lpsouza** [phonegap/phonegap-plugin-contentsync#28]
I'm using Visual Studio 2015 RC to a project in Cordova and decided to use the ContentSync plugin to sync my files. I made a compilation for *Windows Phone (Universal)* and when I try to use the plugin, it appears as return on error: **Missing Command Error**.

I tried to debug the Sync.cs but could not figure out something useful.

Anyone ever been in this situation?

**Comment by stefanoavancini** [comment]
Same error here. Did you resolve the issue?

**Comment by snehasis** [comment]
Which version of windows you are trying ? 8 or 10 ?

**Comment by lpsouza** [comment]
@snehasis and @stefanoavancini I use Windows 8.1. I discover what is the problem. The phonegap-plugin-contentsync is **not supported** on _Windows Universal Apps_. Thanks for the answer. We will waiting a stable version to use on _Windows Universal Apps_.
