### ISSUE TITLE
Will Apple reject my app if I use this plugin?

### ISSUE THREAD

**Issue by andrecardoso** [phonegap/phonegap-plugin-contentsync#32]
Hi,

According to Apple's submission [guidelines](https://developer.apple.com/app-store/review/guidelines/#functionality), item 2.7:
> Apps that download code in any way or form will be rejected

Has someone submitted an app that uses this plugin with success?

**Comment by shazron** [comment]
It is allowed. See https://developer.apple.com/programs/terms/ios/standard/ios_program_standard_agreement_20140909.pdf section 3.3.2
