### ISSUE TITLE
Does Android clearCache affect localStorage or sessionStorage?

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-plugin-contentsync#34]
In a recent commit to Android (1f82930e03d5d3c5267664f5e24b4cfaa651ee58), we clear the browser cache to ensure that the last files are always retrieved by the browser.

We should ensure that this does not affect the application state - `localStorage` or `sessionStorage`.

**Comment by mwbrooks** [comment]
I altered the Hello World app to report the current app state and then update the state:

```javascript
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
        alert(
            'localStorage.firstName:  ' + localStorage.firstName + '\n' +
            'sessionStorage.lastName: ' + sessionStorage.lastName + '\n' +
            'document.cookie: ' + document.cookie
        );
        localStorage.firstName = 'Foo';
        sessionStorage.lastName = 'Bar';
        document.cookie = 'fullName=Foo Bar';
    },
```

Multiple reloads continue to keep the `localStorage` and `sessionStorage` state. The `document.cookie` value is always undefined. _However, this appears to be normal for Android (?)._

Closing the PhoneGap Developer App, relaunching, and reconnecting to the server will retain the `localStorage` state and reset the `sessionStorage` state. _Since cookies appear to be disabled, I think this is normal behaviour._

I could use some verification from @macdonst.

**Comment by macdonst** [comment]
@mwbrooks My initial reading of the clearCache method indicated it would not mess with localStorage but I will run your test and report back.

**Comment by mwbrooks** [comment]
Thanks man! No rush - aim for tomorrow morning?

**Comment by macdonst** [comment]
@mwbrooks yup, verified that local storage and session storage persist post the Android call to clearCache.
