### ISSUE TITLE
Download inside a specific folder

### ISSUE THREAD

**Issue by hashg** [phonegap/phonegap-plugin-contentsync#38]
My scenario is 
`app.zip`
`sub01.zip`
`sub02.zip`

Now I want to first download `app.zip`, then unzip `sub01.zip` and `sub02.zip` inside `app` folder.
```
app
 |
 +-- sub01
 |
 +-- sub02
```

How can I do it? This allows me to add `sub03` or `sub04` later in future.

**Comment by macdonst** [comment]
Try the following:

```
var sync = ContentSync.sync({ src: 'http://myserver/assets/app.zip', id: 'app', type: 'replace' });

sync.on('complete', function(data) {
  var sync2 = ContentSync.sync({ src: 'http://myserver/assets/sub01.zip', id: 'app/sub01', type: 'merge' });
});
```

**Comment by revolunet** [comment]
i can confirm this works

**Comment by hashg** [comment]
I'm between builds. I will try it over the weekend. Thanks for @revolunet confirming it.
