### ISSUE TITLE
copyCordovaAssets

### ISSUE THREAD

**Issue by ravi155** [phonegap/phonegap-plugin-contentsync#39]
Hi,

firstly i'd like to tell how much i like your plugin! Grate work!

On iOS i managed to do everything i desired (have 2 separate html files, one is main application second is downloader)
When app detects new version on server goes to downloader, it downloads new content, then copy cordova assets, and redirects to this new content.

iOS works perfectly. Android not so much.
New application downloaded does not see cordova.js, like it is not copied to destination.
I tried debugging with logcat, and adding more logging points. But from what i see, there is no error when copying cordova assets. Do you have any idea what can be wrong, or how check where cordova assets are copied, maybe wrong path? I'm stuck in front of a wall, have no experience in java at all ...

Any idea?

Best
Rafal

**Comment by denisbabineau** [comment]
I don't know if iOS does the same but I've noticed that on Android it copies the content in the 'www' sub-foldler. (i.e. if you pass in id:'app', you'll find app/www/cordova.js) I would have expected it to copy in app/cordova.js myself otherwise it means you need to nest your content (at least your main html) in a 'www' sub-folder in your archive. This might be a bug?

**Comment by ravi155** [comment]
oh my.... 

in iOS its copied flat to folder it created with new content.
So it is two different behaviours, i assume this is a bug..

**Comment by macdonst** [comment]
@ravi155 Yes, the behaviour should be consistent. I will check with the other implementers and we'll get it sorted.

**Comment by macdonst** [comment]
@ravi155 So on iOS if the appId dir has a www directory it will copy the cordova assets to there, if not it just drops them into appId. I'm going to make Android work the same way.

**Comment by macdonst** [comment]
Okay, I fixed it so Android works the same as iOS.
