### ISSUE TITLE
Support `trustAllHosts` flag for self-signed certificates

### ISSUE THREAD

**Issue by blefebvre** [phonegap/phonegap-plugin-contentsync#56]
The Cordova file-transfer plugin supports a flag to indicate that self-signed certificates should be accepted (`trustAllHosts` at [0]). I recognize that while this is not a safe practice in prod, it can be useful during development.

Would it be possible to support this flag as one of the `sync()` options?

[0] https://github.com/apache/cordova-plugin-file-transfer#download

**Comment by imhotep** [comment]
@blefebvre Can you test this please so that we close the issue ?

**Comment by blefebvre** [comment]
+1, works for me.

**Comment by macdonst** [comment]
@blefebvre did you test iOS and Android?

**Comment by blefebvre** [comment]
I found that iOS couldn't even make an XHR to query if an update was available on the untrusted server, but this was not an issue with the plugin. Android worked as expected.

**Comment by macdonst** [comment]
Woot! Let's close this thang.
