### ISSUE TITLE
`id` param containing a '/' returns error code 4 on iOS

### ISSUE THREAD

**Issue by blefebvre** [phonegap/phonegap-plugin-contentsync#57]
To reproduce, clone https://github.com/blefebvre/phonegap-contentsync-plugin-issue and run `cordova platform add ios && cordova run ios`.

Result:
![screen shot 2015-08-11 at 5 01 48 pm](https://cloud.githubusercontent.com/assets/1048207/9211143/263bca72-404e-11e5-97c8-0f7d4db59817.png)

The `sync` works fine if '/' is removed from the id: https://github.com/blefebvre/phonegap-contentsync-plugin-issue/blob/master/www/js/index.js#L38

Works as expected on Android.

**Comment by mwbrooks** [comment]
I can't think of a major side-effects to Simon's commit. @imhotep should also review it though.

Also, thanks @macdonst for cleaning up the whitespace.

**Comment by macdonst** [comment]
Merged

**Comment by blefebvre** [comment]
Is it possible that error code 4 could happen again? If so, can we add an entry to the ERROR_STATE enumeration?

**Comment by imhotep** [comment]
doubtful
