### ISSUE TITLE
Feat: copyRootApp if it hasn't been done before

### ISSUE THREAD

**Issue by voliva** [phonegap/phonegap-plugin-contentsync#59]
It would be nice and more understandable that "local" with "copyRootApp" with src = "null" checked if the directory exists, or just some way to identify this case from Javascript.

The use case for that is when using contentsync to manage application updates, to simplify the management between when to use the cordova path and when to use the PERSISTENT path.

As an example:
-> We distribute an app with version = 1, a fresh install. When we install this app, all we can do at this moment is to use the cordova path (in android, file:///android_asset/www/index.html).
-> We put an update with version = 2. When we launch the app, we detect that there's a new version and call content-sync to download it. Then somehow we have to change the starting path from cordova path to persistent path. And if you want to manage incremental updates, then it gets harder, since you have to download from the server the "base" application (that you already have, but in cordova path) to "merge" those updates.

If we were to use {"copyRootApp", "local", "src":null}, then we have the problem that we somehow, from javascript, have to know if it's already been done before, or else all the stuff we've updated will get overriden by our outdated application that's lying in cordova path.

What would be nice to have then is a function like "copyOnlyIfDirectoryDoesn'tExist", that reading the documentation it should be what "local" does, but then looking at the code, you can see that if src is null, then it overrides everything regardless if the directory already exists or not. Actual code:

    if (type.equals(TYPE_LOCAL)) {
        if ("null".equals(src) && (copyRootApp || copyCordovaAssets)) {
            if (copyRootApp) {
                copyRootApp(outputDirectory);
            }
            if (copyCordovaAssets) {
                copyCordovaAssets(outputDirectory);
            }

        } else if (!dir.exists()) {
            type = TYPE_REPLACE;
        }
    }

As a workaround/hack, I can do something like {"copyRootApp", "local", "src":"path_to_a_blank_zip"}, but that's really, really ugly (plus, you need an internet connection for that)

**Comment by macdonst** [comment]
@voliva That's not a feature request that's a bug.

**Comment by voliva** [comment]
Oh ok, thanks for the info!

I thought it was done on purpose for a way of "reseting" everything as how it was originally or something like that...

**Comment by macdonst** [comment]
@voliva no, if you want to reset you can just delete the local copy and start again. That is probably the cleanest.

**Comment by macdonst** [comment]
@voliva fixed in master.
