### ISSUE TITLE
Sync should support non zip archives

### ISSUE THREAD

**Issue by imhotep** [phonegap/phonegap-plugin-contentsync#62]
Right now when calling sync() everything gets extracted by default. cf: [pull request](https://github.com/phonegap/phonegap-plugin-contentsync/pull/48) by @revolunet 
Not sure what the best way is to detect if an archive is a zip archive:
- Read the first 4 bytes and expect "50 4B” PK
- Rely on file extension to be ".zip"
- All of the above?

Use case is for all other file types: images, videos, etc...

**Comment by revolunet** [comment]
in my PR, the file is considered a zip if matches one of these :
 - server content-type
 - or file has a ".zip" extension

to make the code more focused and simpler, what about moving the "copy cordova" stuff to dedicated methods ?
