### ISSUE TITLE
[iOS] copyRootApp has not effect

### ISSUE THREAD

**Issue by Avareto** [phonegap/phonegap-plugin-contentsync#69]
I am wondering why 'copyRootApp: true' is not working as expected.
When I call "var sync = ContentSync.sync({ src: url, id: 'myapps', type: 'replace', copyCordovaAssets: false, copyRootApp: true);" (taken from the sample on github) it just downloads and extracts the content into the target directory (sync folder). But nothing is copied from the original www folder of the installed app to that sync folder location. Any idea what's going wrong?

**Comment by imhotep** [comment]
@Avareto Which platform ?

**Comment by Avareto** [comment]
iOS

**Comment by imhotep** [comment]
Just got around into doing this. Let me know if version 1.1.13 fixes it for you!

**Comment by Avareto** [comment]
Now it works. Thanks!!!
