### ISSUE TITLE
Change id in plugin.xml

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-contentsync#7]
Hey, 

Can we change the plugin ID from "com.adobe.phonegap.content-sync" to "com.adobe.phonegap.contentsync" as package names can't have hyphens in Java?

**Comment by mwbrooks** [comment]
Yup that's fair! Let's just ensure that the iOS and WP code bases work
after the ID change!

**Comment by macdonst** [comment]
@mwbrooks Yeah, that's what I'm waiting on. Had some emergency stuff to take care of for Marketing Summit for the AEM guys and didn't get a chance to talk to @imhotep and @timkim.

**Comment by purplecabbage** [comment]
Class and variable names should not be dependent on plugin id. You can call the Java class whatever you want, as long as it matches what's in plugin.xml
If this was a restriction then cordova-plugin-device would be broken, along with half the core cordova plugins. 
If you are renaming this, it should probably have an id of phonegap-plugin-contentsync to fit in the npm world.

**Comment by macdonst** [comment]
@purplecabbage good call, I made that the ID when I fixed this issue. Submitting to NPM later today.
