### ISSUE TITLE
[iOS] sample download operation crashes

### ISSUE THREAD

**Issue by Avareto** [phonegap/phonegap-plugin-contentsync#70]
I created a simple cordova App from the sample code, without changing any of the sample JavaScript. The App crashes and exists when I press the download button. When I run it in Xcode an exception is thrown after the files have been dowloaded. Only the sync operation works as expected.

**Comment by imhotep** [comment]
Forgot to update this one. This should be fixed now too along with Issue #76 . If you could give it another try.
