### ISSUE TITLE
SSZipArchive conflict with other installed plugin - iOS

### ISSUE THREAD

**Issue by jeroendeswaef** [phonegap/phonegap-plugin-contentsync#71]
After adding the plugin, I got an ld linking error:

    duplicate symbol _OBJC_IVAR_$_SSZipArchive

This is probably because I already have this plugin installed: https://github.com/MobileChromeApps/cordova-plugin-zip, that also makes use of the minizip library.

Output of `find . -name "SSZipArchive*"` :

    ./Plugins/org.chromium.zip/Plugins/minizip/SSZipArchive.h
    ./Plugins/org.chromium.zip/Plugins/minizip/SSZipArchive.m
    ./Plugins/phonegap-plugin-contentsync/minizip/SSZipArchive.h
    ./Plugins/phonegap-plugin-contentsync/minizip/SSZipArchive.m

I know this issue is not your fault, but more an issue on the integration of 2 libraries.

What I wanted to know is what would be the best option to resolve those kind of issues. Is there some flag to use an existing version of minizip? Or would you try to remove one of the minizip directories?

Thanks in advance,
Jeroen

**Comment by imhotep** [comment]
This plugin supports the same api as cordova-plugin-zip so you don't need to have both of them installed.
