### ISSUE TITLE
iOS: download which results in a 404 leaves the error page in place

### ISSUE THREAD

**Issue by tripodsan** [phonegap/phonegap-plugin-contentsync#77]
When starting a content sync to a URL that results in a 404, leaves the error response in the file system and unzipping fails. 

Example:
```
var sync = ContentSync.sync({
  src: 'http://www.google.com/foo.zip',
  type: 'merge',
  id: 'myapp',
  copyRootApp: true
});
```
does never trigger onError but on complete:
`localPath: ".../Data/Application/1DE1EC18-3965-4275-A119-A02DD651AEE4/Library/foo.zip"`

the response from google is correct:

```
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
X-Content-Type-Options: nosniff
Date: Wed, 28 Oct 2015 05:16:51 GMT
Server: sffe
Content-Length: 1576
X-XSS-Protection: 1; mode=block

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
...
```

and the `foo.zip` contains the HTML contents of the 404 response.

**Comment by imhotep** [comment]
@tripodsan Thanks for reporting this. When you get a chance try version 1.1.14 and let me know if it fixes your issue so that I can close it.

**Comment by tripodsan** [comment]
Thanks. I created a test case. see PR #80. Works for me now.
