### ISSUE TITLE
Content sync location is not consistent in respect to cordova file plugin on iOS and Android

### ISSUE THREAD

**Issue by tripodsan** [phonegap/phonegap-plugin-contentsync#83]
Test if the local copy is at the correct place and can be accessed via file plugin.
On android this works, as the files are copied to the PERSISTENT location:

`/data/data/<app-id>/files`

on iOS the files are copied to

`/var/mobile/Applications/<UUID>/Library`  (or .../Documents in compatibility mode)

but the persistent directory is `.../Library/files`, so they can't be accessed.

the only work around is to distinguish the platform in the code and use different content roots.

see https://github.com/tripodsan/phonegap-plugin-contentsync/commit/d2b7d2612cb05a3b5574a63dafc09906cc051544

**Comment by macdonst** [comment]
@tripodsan actually the PERSISTENT location on Android is:

`/data/data/<app-id>/files/files` 

as per https://github.com/apache/cordova-plugin-file/blob/a26070f435b810ceabc3c82efcc8294820be737b/src/android/FileUtils.java#L182. Why is there a double 'files', I don't know. I believe it was added in error but I can't change it now or it will break all existing Android apps that rely on that location.

If you use an app id of `files/myapp` then it will end up dropping the files in PERSISTENT file location for both platforms. Let us know if that doesn't work for you. We should probably document it in our README.

**Comment by tripodsan** [comment]
but see my tests in https://github.com/tripodsan/phonegap-plugin-contentsync/commit/d2b7d2612cb05a3b5574a63dafc09906cc051544 they work on android and fail on iOS.

the reported directories are:

```
android:
sync id: local/test1446831637634
localPath: /data/data/io.cordova.hellocordova/files/files/local/test1446831637634
fs root: file:///data/data/io.cordova.hellocordova/files/files/

ios:
sync id: local/test1446832023584
localPath: /Users/tripod/Library/Developer/CoreSimulator/Devices/839CA493-C73E-4FD9-AC70-1B0D7B867666/data/Containers/Data/Application/F4F2861B-F542-45DB-96B4-983095733AE3/Library/local/test1446832023584
fs root: file:///Users/tripod/Library/Developer/CoreSimulator/Devices/839CA493-C73E-4FD9-AC70-1B0D7B867666/data/Containers/Data/Application/F4F2861B-F542-45DB-96B4-983095733AE3/Library/files/
````

but it might be that the PERSISTENT root on iOS is wrong... @shazron mentioned something.

**Comment by tripodsan** [comment]
I would try to be consistent with the _cordova-plugin-file_ and use whatever `dataDirectory` they use as root.

on android: `/data/data/<app-id>/files`
on ios: `/var/mobile/Applications/<UUID>/Library/NoCloud`
on osx: `~/Library/Application Support/<bundle-id>/files`

**Comment by macdonst** [comment]
@tripodsan Seems legit and the other plugin maintainers agree so I'll work on it tomorrow.

**Comment by tripodsan** [comment]
commit looks good to me.
