### ISSUE TITLE
Initial local copy fails if it contains a file the is enumerated before the first directory

### ISSUE THREAD

**Issue by tripodsan** [phonegap/phonegap-plugin-contentsync#84]
consider the following contents of `www`

```
www
├── anyfile.txt
├── cdvtests/
├── cordova-js-src/
├── cordova.js
├── cordova_plugins.js
├── css/
├── img/
├── index.html
├── js/
└── plugins/
```

The initial local copy fails, because the `anyfile.txt` is enumerated before the firs directory. The copy algorithm only creates intermediate directories for nested files.

**Comment by macdonst** [comment]
@tripodsan does the only the copy of _test_file.txt fail or does the copy of all the files fail? The reason I ask is IIRC android packager ignores any files that start with an '_' when packaging the assets folder.

**Comment by tripodsan** [comment]
the problem is, that non of the files are copied before the first directory. I chose `_` just for clarity. but It could also be `anyfile.txt`

**Comment by tripodsan** [comment]
see https://github.com/tripodsan/phonegap-plugin-contentsync/tree/issue-84/

**Comment by tripodsan** [comment]
here's the fix: https://github.com/tripodsan/phonegap-plugin-contentsync/commit/efa5c2e0dba0d805ef328cad5decc1c1e9f3417d

**Comment by macdonst** [comment]
@tripodsan kk, just making sure because Android is weird about files that start with `_`.

If you have push rights to this repo then go ahead an push the code as I did a quick review. If not send a PR and I'll merge later. 

Can't believe you got me interested in this when you already had a fix. I could've gone to sleep 30 minutes ago ;)

**Comment by macdonst** [comment]
Oh and now I see the next email is a PR :+1:

**Comment by tripodsan** [comment]
sorry...didn't want to keep you awake.... I was preparing the PR as a breakfast gift :-)

**Comment by macdonst** [comment]
Merged PR.
