### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-contentsync#9]
Do we need a LICENSE file for this repo? Do each of the source files need to include the license header?

**Comment by mwbrooks** [comment]
For PhoneGap projects, we usually have a LICENSE for Apache 2.0 and a
NOTICE if third-party libraries are vendored. We don't bother adding the
license to every header.

**Comment by macdonst** [comment]
I added a LICENSE and NOTICE file. If anyone is using 3rd party libs, add them to NOTICE.
